### PR TITLE
Added cross-env to support windows

### LINKED ISSUE #22: Use cross-env to support Windows for development
We are using bash variables here in our scripts, which isn't supported in DOS environment.

In order to support windows, we can use [cross-env](https://www.npmjs.com/package/cross-env) (add to devDependencies using `npm i -D cross-env`) and simply prepend cross-env in our scripts;

```diff
-    "test": "NODE_ENV=test jest && npm run lint",
+    "test": "cross-env NODE_ENV=test jest && npm run lint",
```

```diff
-    "start": "NODE_ENV=production node server"
+    "start": "cross-env NODE_ENV=production node server"
  },
```

### PR DESCRIPTION
**Pull request by twishasaraiya**
Fixes #22.
No error occurred this time while running `git push origin master`

### CODE REVIEW

**Comment by bogas04** [comment]
Thanks a lot for speedy development!

@twishasaraiya I think your linebreak isn't set correctly, you can see that entire package.json was changed. Could you please look into it?

**Comment by twishasaraiya** [comment]
Since it is windows it was originally saved with CRLF. I had to change the settings in my editor and resave. That I think triggered the entire file to change from CRLF to LF.

**Comment by twishasaraiya** [comment]
What should I do now??

**Comment by bogas04** [comment]
@twishasaraiya coz of LF/CRLF issue, merge conflicts are harder to debug coz every single line seems to have been changed. I'll resolve it, don't worry.

**Comment by bogas04** [comment]
@twishasaraiya can you add cross-env to devDependencies? `npm i -D cross-env`

**Comment by twishasaraiya** [comment]
I have added it to my local copy but the problem again is that when I save my file my editor changes each line from CRLF to LF. If I commit again the whole file will be changed.

**Comment by twishasaraiya** [comment]
I was working on SVG icons and when I tried to do `git pull` it asked me to commit changes first and also there were merge conflicts for `package.json`. What should I do now since SVG icons commit is not related to this PR. Should I close this PR and create a new one??

**Comment by bogas04** [comment]
@twishasaraiya both are unrelated and PR has nothing to do with it. The problem is that you started working on same branch.
This is what you need to do;

Short method (you lose existing work);
* Delete your repo
* Fork again
* Now you'll have latest master branch
* branch out to a new branch (e.g; `git checkout -b add-svg`)
* Then push it and raise a PR from add-svg to master of this repo.

Long (everything is preserved);
* Reset your master branch to the point your changes are not committed
* Fetch upstream
* rebase upstream/master to your master branch. 
* branch out to a new branch (e.g; `git checkout -b add-svg`)
* Then push it and raise a PR from add-svg to master of this repo.

**Comment by twishasaraiya** [comment]
Okay. Thank you. 
Sorry for the delay. I will make PR again as soon as possible.
Closing #24.

**Pull request closed without merging**
