### PR TITLE
Husky

### PR DESCRIPTION
**Pull request by darthgera123**
Added Husky and Lint in precommit while husky is in prepush as well
solves issue #1 
also might wanna check into Item.test.js

### CODE REVIEW

**Comment by bogas04** [comment]
@darthgera123 Thank you for the PR.

Few things;

* I'm not really a fan of precommit hooks as you tend to break stuff (tests/lints) during development cycle and then fix them before raising a PR or pushing to remote. So it'll be nice if we could only have prepush hook for now, and if it feels necessary, we can go for precommit hooks later. Makes sense?

* I see that you're using lint-staged and `git add`ing it precommit. This too causes problems when the linter performs incorrect job on the files. This has happened to my other project wherein prettier incorrectly prettified. And since we git add silently, it's bit harder to understand what changed and what caused the bug. It'll be nice if we let the linter throw the error and then let developer do something about it.

* `npm run pretty` isn't a script, right? I think you probably want to run `eslint .`

**Comment by darthgera123** [comment]
Got it will make changes

**Comment by darthgera123** [comment]
set eslint to airbnb standards and activated for react

**Comment by bogas04** [comment]
@darthgera123 awesome!

I noticed you introduced an eslintrc file, however we already have one here 

https://github.com/GirlScriptSummerOfCode/Upay/blob/master/.eslintrc.js

**Comment by bogas04** [comment]
One more thing, actually two;

* We don't have a src folder. You'll want to run eslint for entire project.
* Could you please not use --fix? Automatically fixing lint issues can impose unexpected issues post commit. 

I'm sorry for pestering you with so many comments!

**Comment by darthgera123** [comment]
Not an issue. Just a clarification -
1. Should I make the entire repo as src folder so it will run on it anyway.
This stuff anyway confused me a lot initially but setting it right now is helping me understand it.

**Comment by bogas04** [comment]
You can move everything to src (I'd prefer client/ and server/ folders at root level), but'll have to ensure next.js works with this properly. I guess we can make it work but it'll be some work.

Let's not do it right now, maybe in future we can make that change.

For now, just pass ./ to eslint in the lint script.

**Comment by darthgera123** [comment]
Cool will do

**Pull request merged**
